name: "Build and Release Swiftfin"
 
on:
  workflow_dispatch:
    inputs:
      bundle_id:
        description: "Modify the bundle ID (optional)"
        default: "org.jellyfin.swiftfin"
        required: false
        type: string
      app_name:
        description: "Modify the name of the app on the Home Screen (optional)"
        default: "Swiftfin"
        required: false
        type: string
 
jobs:
  build:
    name: Build Swiftfin
    runs-on: macos-14
    permissions:
      contents: write
 
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
 
      - name: Checkout Main
        uses: actions/checkout@v4.1.6
        with:
          submodules: recursive
 
      - name: Install Dependencies
        run: |
          brew install ldid dpkg make
          brew install swiftgen
          carthage update --use-xcframeworks --cache-builds
 
      - name: Set Xcode Version
        run: sudo xcode-select -s "/Applications/Xcode_16.app"

      - name: Cache Carthage
        uses: actions/cache@v4
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: ${{ runner.os }}-carthage-

      - name: Update Carthage
        run: carthage update --use-xcframeworks --cache-builds

      - name: Build the Project
        run: |
          xcodebuild clean build \
          -project "Swiftfin.xcodeproj" \
          -scheme "Swiftfin tvOS" \
          -configuration Release \
          -clonedSourcePackagesDirPath PackageCache \
          -derivedDataPath build/derived_data \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
 
      - name: Create Payload Directory
        run: mkdir -p build/Payload
 
      - name: Copy App to Payload
        run: |
          find build/derived_data/Build/Products/*
          cp -r build/derived_data/Build/Products/Release-appletvos/"Swiftfin tvOS.app" build/Payload
 
      - name: Fake Code Sign the App
        run: ldid -S build/Payload/"Swiftfin tvOS.app"/"Swiftfin tvOS"
 
      - name: Package IPA
        run: |
          cd build
          zip -r Swiftfin.ipa Payload
 
      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Swiftfin-ipa
          path: build/Swiftfin.ipa
