on:
  repository_dispatch:
    types: [draft_release]
  
jobs:
  test_build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.JF_BOT_TOKEN }}
          fetch-depth: 0
      
      - name: Create Release
        run: fastlane draftReleaseLane \
          repository:${{ github.event.client_payload.repository }} \
          apiToken:${{ github.event.client_payload.apiToken }} \
          tag:${{ github.event.client_payload.tag }} \
          name64:${{ github.event.client_payload.name64 }}