on:
  repository_dispatch:
    types: [tag]
  
jobs:
  test_build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.JF_BOT_TOKEN }}
          fetch-depth: 0
      
      - name: Add Tag
        run: fastlane tagLane \
          tag:${{ github.event.client_payload.tag }} \
          commit:${{ github.event.client_payload.commit }}